/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciocongrafica;

/**
 *
 * @author jdsa1
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        goToFormularioDos = new javax.swing.JButton();
        goToSignIn = new javax.swing.JButton();
        goToEjemploDeGrafica = new javax.swing.JButton();
        closeOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menú Principal");

        goToFormularioDos.setText("Calculadora de área");
        goToFormularioDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFormularioDosActionPerformed(evt);
            }
        });

        goToSignIn.setText("Inicio de Sesión");
        goToSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSignInActionPerformed(evt);
            }
        });

        goToEjemploDeGrafica.setText("Calculadora");
        goToEjemploDeGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToEjemploDeGraficaActionPerformed(evt);
            }
        });

        closeOut.setText("Cerrar");
        closeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeOut)
                    .addComponent(goToEjemploDeGrafica)
                    .addComponent(goToSignIn)
                    .addComponent(goToFormularioDos)
                    .addComponent(jLabel1))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(goToFormularioDos)
                .addGap(18, 18, 18)
                .addComponent(goToSignIn)
                .addGap(18, 18, 18)
                .addComponent(goToEjemploDeGrafica)
                .addGap(18, 18, 18)
                .addComponent(closeOut)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeOutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeOutActionPerformed

    private void goToFormularioDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFormularioDosActionPerformed
        // TODO add your handling code here:
        formulariodos formudos = new formulariodos();
        formudos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goToFormularioDosActionPerformed

    private void goToSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSignInActionPerformed
        // TODO add your handling code here:
        inicioSesion sesion = new inicioSesion();
        sesion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goToSignInActionPerformed

    private void goToEjemploDeGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToEjemploDeGraficaActionPerformed
        // TODO add your handling code here:
        ejemploDeGrafica formuno = new ejemploDeGrafica();
        formuno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goToEjemploDeGraficaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeOut;
    private javax.swing.JButton goToEjemploDeGrafica;
    private javax.swing.JButton goToFormularioDos;
    private javax.swing.JButton goToSignIn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
